name: Ranked_Rods
version: 1.0.0
author: John_Willikers
main: com.johnwillikers.fisher.FishingRewards
description: Makes Catching fish pretty lit
commands:
  rr:
    description: Used to interact with Ranked Rod
    aliases: [rankedrod, rod]
    usage: /rr help
    permission: rr.reload
    permission-message: You do not have sufficient permissions.